[package]
name = 'Homework5'
version = '1.0.0'
[addresses]
basic_address = '0x1'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'